name: Build & Deploy Backend
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: bahmutov/npm-install@v3

      - name: Build project
        run: npm run build
        env:
          PORT: 3000
          DB_URL: ${{ secrets.DB_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PORT: 3000
          DB_URL: ${{ secrets.DB_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}